#server:
#  port: 8090
#  servlet: 
#    encodig: UTF-8
#    enabled: true 
#  
#  
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#    static-path-pattern: /resources/**
#    
#  datasource: 
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/jpatest
#    username: root
#    password: 7564
#   
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:   
#      format_sql: true
#      highlight_sql: true
#      use_sql_comments : true
#   
#  mandatory-file-encoding: true
#  
#  servlet:
#    multipart:
#      max-file-size: 1000MB
#      max-request-size: 1000MB 
#     
#  logging: 
#    level: 
#      org:
#        hibernate:
#          type:
#            descriptor:
#              sql: trace
#                  
#
